"""Introduction and Motivation — Why RFdiffusion and what it promises."""

from gaia.lang import claim, setting, noisy_and

# --- Settings: established background ---

ddpm_definition = setting(
    "Denoising diffusion probabilistic models (DDPMs) are a class of generative "
    "machine learning models that learn to reverse a gradual noising process. "
    "They are trained to denoise data (images, text, protein structures) corrupted "
    "with Gaussian noise, and by stochastically reversing this corruption, they "
    "generate diverse outputs resembling the training data.",
    title="Definition of DDPMs",
)

rosettafold_definition = setting(
    "RoseTTAFold (RF) is a protein structure prediction network that generates "
    "protein structures with high precision, operates on a rigid-frame representation "
    "of residues (Cα coordinate and N-Cα-C orientation per residue) with rotational "
    "equivariance, and has an architecture enabling conditioning on design specifications "
    "at the individual residue, inter-residue distance and orientation, and 3D coordinate levels.",
    title="RoseTTAFold structure prediction network",
)

alphafold2_definition = setting(
    "AlphaFold2 (AF2) is a highly accurate protein structure prediction method "
    "that predicts 3D protein structures from amino acid sequences. In this work, "
    "AF2 is used as an independent validation tool: a design is considered an "
    "in silico 'success' if AF2 predicts its structure with high confidence.",
    title="AlphaFold2 as validation tool",
)

proteinmpnn_definition = setting(
    "ProteinMPNN is a deep learning network for protein sequence design. Given a "
    "protein backbone structure, it designs amino acid sequences that encode that "
    "structure. In the RFdiffusion pipeline, ProteinMPNN is used to design sequences "
    "for the backbone structures generated by RFdiffusion, typically sampling eight "
    "sequences per design.",
    title="ProteinMPNN for sequence design",
)

protein_design_goal = setting(
    "De novo protein design seeks to generate proteins with specified structural "
    "and/or functional properties, for example, making a binding interaction with "
    "a given target, folding into a particular topology, or containing a catalytic site.",
    title="Goal of de novo protein design",
)

in_silico_success_definition = setting(
    "In silico 'success' is defined as an RFdiffusion output for which the AF2 "
    "structure predicted from a single sequence satisfies three criteria: "
    "(1) high confidence (mean predicted aligned error, pAE, less than 5), "
    "(2) globally within 2 Å backbone root mean-squared deviation (r.m.s.d.) of "
    "the designed structure, and (3) within 1 Å backbone r.m.s.d. on any scaffolded "
    "functional site. This measure correlates with experimental success and is more "
    "stringent than TM-score-based metrics.",
    title="In silico success metric",
)

# --- Claims: propositions that can be questioned ---

ddpm_properties_for_protein_design = claim(
    "DDPMs have three properties well suited to protein design: "
    "(1) they generate highly diverse outputs because each denoising trajectory "
    "starts from different noise and follows a stochastic path; "
    "(2) they can be guided at each step towards specific design objectives through "
    "conditioning information; "
    "(3) rotationally equivariant DDPMs can model 3D protein structures in a global "
    "reference frame independent manner.",
    title="DDPM properties suited for protein design",
    background=[ddpm_definition],
)

prior_ddpm_limitations = claim(
    "Previous attempts to adapt DDPMs for protein monomer design (by conditioning "
    "on small protein 'motifs' or on secondary structure and block-adjacency information) "
    "showed limited success in generating sequences that fold to intended structures "
    "in silico, probably due to the limited ability of the denoising networks to "
    "generate realistic protein backbones, and were not tested experimentally.",
    title="Limitations of prior protein diffusion methods",
)

rf_inpainting_limitations = claim(
    "RFjoint Inpainting, a method that fine-tuned RoseTTAFold to complete protein "
    "backbones around input functional motifs in a single step, demonstrated that "
    "the method can scaffold a wide range of protein functional motifs with atomic "
    "accuracy. However, RFjoint Inpainting fails on minimalist site descriptions "
    "that do not sufficiently constrain the overall fold and, because it is "
    "deterministic, can produce only a limited diversity of designs for a given problem.",
    title="RFjoint Inpainting limitations",
)

key_insight = claim(
    "By fine-tuning the RoseTTAFold structure prediction network on protein structure "
    "denoising tasks — rather than using it deterministically — a generative diffusion "
    "model can be obtained that overcomes the limitations of both prior DDPMs (poor "
    "backbone quality) and RFjoint Inpainting (limited diversity, failure on minimal "
    "specifications). Because the starting point is random noise, each denoising "
    "trajectory yields a different solution, and because structure is built up "
    "progressively through many denoising iterations, little to no starting structural "
    "information is required.",
    title="Key insight: fine-tuning RF as diffusion denoiser",
    background=[rosettafold_definition, ddpm_definition],
)

rfdiffusion_broad_success = claim(
    "RFdiffusion achieves outstanding performance on unconditional and "
    "topology-constrained protein monomer design, protein binder design, symmetric "
    "oligomer design, enzyme active site scaffolding, and symmetric motif scaffolding "
    "for therapeutic and metal-binding protein design.",
    title="RFdiffusion achieves broad design success",
    background=[protein_design_goal],
)

# --- Strategies ---

_strat_key_insight = noisy_and(
    [ddpm_properties_for_protein_design, prior_ddpm_limitations, rf_inpainting_limitations],
    key_insight,
    reason=(
        "The authors reasoned that improved diffusion models for protein design could be "
        "developed by leveraging the deep understanding of protein structure implicit in "
        "structure prediction networks. @ddpm_properties_for_protein_design establishes "
        "that DDPMs have desirable properties for protein design (diversity, conditionability, "
        "equivariance). @prior_ddpm_limitations shows that previous protein DDPMs failed "
        "because their denoising networks could not generate realistic backbones. "
        "@rf_inpainting_limitations shows that while RF-based single-step inpainting worked, "
        "it was deterministic (limited diversity) and required substantial starting information. "
        "Combining DDPMs' stochastic iterative generation with RF's understanding of protein "
        "structure addresses both limitations: each trajectory from random noise yields a "
        "different solution (overcoming determinism), and iterative denoising progressively "
        "builds structure (overcoming the need for starting information)."
    ),
    background=[rosettafold_definition, ddpm_definition],
)
