"""Technical Approach — How RFdiffusion works: noising, denoising, training strategies."""

from gaia.lang import claim, setting, noisy_and

from .motivation import (
    rosettafold_definition,
    ddpm_definition,
    alphafold2_definition,
    proteinmpnn_definition,
    in_silico_success_definition,
    key_insight,
)

# --- Settings ---

pdb_training_data = setting(
    "RFdiffusion training inputs are generated by noising protein structures sampled "
    "from the Protein Data Bank (PDB) for up to 200 steps. For translations, Cα "
    "coordinates are perturbed with 3D Gaussian noise. For residue orientations, "
    "Brownian motion on the manifold of rotation matrices is used.",
    title="PDB-based noising for training data generation",
)

frame_representation = setting(
    "RFdiffusion uses the RoseTTAFold frame representation comprising a Cα coordinate "
    "and N-Cα-C rigid orientation for each residue. This representation is rotationally "
    "equivariant.",
    title="RF frame representation",
)

# --- Claims ---

mse_loss_design = claim(
    "RFdiffusion is trained by minimizing a mean-squared error (m.s.e.) loss between "
    "frame predictions and the true protein structure (without alignment), averaged "
    "across all residues. Unlike the FAPE loss used in RF structure prediction training, "
    "m.s.e. loss is not invariant to the global reference frame and therefore promotes "
    "continuity of the global coordinate frame between timesteps. The m.s.e. loss is "
    "crucial for unconditional generation.",
    title="MSE loss for training RFdiffusion",
    background=[frame_representation, pdb_training_data],
)

denoising_process = claim(
    "To generate a new protein backbone, RFdiffusion first initializes random residue "
    "frames, makes a denoised prediction, and updates each residue frame by taking a "
    "step in the direction of this prediction with some noise added. The reverse step "
    "size and noise are chosen so the denoising process matches the distribution of "
    "the noising process. Through many such steps (typically 200), random frames "
    "converge on realistic protein backbone structures.",
    title="Iterative denoising generation process",
    background=[frame_representation, ddpm_definition],
    metadata={
        "figure": "artifacts/images/14cc1b64b91e3a21683a33d848864cdbe08bf822d5b5e3710c4dfe442319dade.jpg",
        "caption": "Fig. 1 | Protein design using RFdiffusion. Diffusion models for proteins trained to recover corrupted structures via iterative denoising. RF fine-tuned into RFdiffusion with self-conditioning.",
    },
)

self_conditioning_improvement = claim(
    "Self-conditioning — in which the model conditions on its previous prediction "
    "between timesteps, inspired by 'recycling' in AlphaFold2 — notably improved "
    "performance on in silico benchmarks encompassing both conditional and unconditional "
    "protein design tasks. Increased coherence of predictions within self-conditioned "
    "trajectories may at least in part explain these performance increases.",
    title="Self-conditioning improves RFdiffusion performance",
    metadata={
        "figure": "artifacts/images/14cc1b64b91e3a21683a33d848864cdbe08bf822d5b5e3710c4dfe442319dade.jpg",
        "caption": "Fig. 1 | Protein design using RFdiffusion. Diffusion models for proteins trained to recover corrupted structures via iterative denoising. RF fine-tuned into RFdiffusion with self-conditioning.",
    },
)

pretraining_benefit = claim(
    "Fine-tuning RFdiffusion from pretrained RoseTTAFold weights was far more "
    "successful than training for an equivalent length of time from untrained "
    "(randomly initialized) weights, as measured by in silico success rates on "
    "unconditional generation benchmarks.",
    title="Pretraining from RF weights is critical",
    background=[rosettafold_definition],
    metadata={
        "figure": "artifacts/images/a2edf1159fef613aca489410c9267ab0944878967855ac284ddd740f587eb780.jpg",
        "caption": "Fig. 2 | Outstanding performance of RFdiffusion for monomer generation. Unconditional generation, TM-score novelty, AF2 validation, comparison with Hallucination, ablation studies, experimental CD/thermostability.",
    },
)

mse_vs_fape_ablation = claim(
    "Ablating the m.s.e. loss by training with FAPE loss instead notably decreases "
    "the performance of RFdiffusion for unconditional generation of 300 amino acid "
    "proteins, confirming that m.s.e. loss is essential.",
    title="MSE loss ablation shows its necessity",
    metadata={
        "figure": "artifacts/images/a2edf1159fef613aca489410c9267ab0944878967855ac284ddd740f587eb780.jpg",
        "caption": "Fig. 2 | Outstanding performance of RFdiffusion for monomer generation. Unconditional generation, TM-score novelty, AF2 validation, comparison with Hallucination, ablation studies, experimental CD/thermostability.",
    },
)

pipeline_description = claim(
    "The RFdiffusion design pipeline consists of: (1) RFdiffusion generates a protein "
    "backbone structure via iterative denoising, (2) ProteinMPNN designs amino acid "
    "sequences for the backbone (typically 8 sequences per design), (3) AF2 predicts "
    "the structure from each designed sequence for validation. The pipeline can be "
    "conditioned on various inputs including partial sequence, fold information, "
    "symmetry specifications, or fixed functional-motif coordinates.",
    title="RFdiffusion design pipeline",
    background=[proteinmpnn_definition, alphafold2_definition, in_silico_success_definition],
    metadata={
        "figure": "artifacts/images/14cc1b64b91e3a21683a33d848864cdbe08bf822d5b5e3710c4dfe442319dade.jpg",
        "caption": "Fig. 1 | Protein design using RFdiffusion. Diffusion models for proteins trained to recover corrupted structures via iterative denoising. RF fine-tuned into RFdiffusion with self-conditioning.",
    },
)

compute_efficiency = claim(
    "RFdiffusion generation is more compute efficient than unconstrained Hallucination "
    "with RF. A 100-residue protein can be generated in as little as 11 seconds on an "
    "NVIDIA RTX A4000 GPU, compared to approximately 8.5 minutes for RF Hallucination. "
    "Efficiency can be further improved by taking larger steps at inference time and "
    "by truncating trajectories early.",
    title="RFdiffusion compute efficiency",
)

method_design_validated = claim(
    "Ablation studies confirm that both self-conditioning between timesteps and "
    "fine-tuning from pretrained RoseTTAFold weights are each essential for "
    "RFdiffusion's performance: removing either notably decreases in silico "
    "success rates on unconditional generation benchmarks.",
    title="Ablation studies validate method design choices",
)

# --- Strategies ---

_strat_mse_loss = noisy_and(
    [key_insight, mse_vs_fape_ablation],
    mse_loss_design,
    reason=(
        "The choice of m.s.e. loss follows from @key_insight that RF should be fine-tuned "
        "as a diffusion denoiser. Unlike FAPE loss (which is invariant to global reference "
        "frame), m.s.e. loss preserves global coordinate frame continuity between timesteps, "
        "which is essential for the iterative denoising process. @mse_vs_fape_ablation "
        "provides direct empirical confirmation: switching to FAPE notably decreases "
        "unconditional generation performance."
    ),
    background=[frame_representation, pdb_training_data],
)

_strat_ablation = noisy_and(
    [self_conditioning_improvement, pretraining_benefit],
    method_design_validated,
    reason=(
        "@self_conditioning_improvement shows that conditioning on previous predictions "
        "between timesteps notably improved both conditional and unconditional benchmarks. "
        "@pretraining_benefit shows that starting from pretrained RF weights was far more "
        "successful than training from scratch. Together these ablation studies confirm "
        "that the key design choices in the training recipe are each essential."
    ),
    background=[rosettafold_definition],
)

_strat_pipeline = noisy_and(
    [key_insight, denoising_process, method_design_validated],
    pipeline_description,
    reason=(
        "The three-stage pipeline follows from: @key_insight establishes that RF fine-tuned "
        "as a denoiser generates backbone structures; @denoising_process describes the "
        "iterative denoising mechanism; @method_design_validated confirms the training "
        "recipe (self-conditioning + pretrained weights) is essential. ProteinMPNN then "
        "designs sequences for the generated backbones, and AF2 validates them."
    ),
    background=[proteinmpnn_definition, alphafold2_definition, in_silico_success_definition],
)
