"""Design of Higher-Order Symmetric Oligomers — RFdiffusion generates assemblies with any point group symmetry."""

from gaia.lang import claim, setting, noisy_and, abduction

from .motivation import in_silico_success_definition
from .s2_method import pipeline_description

# --- Settings ---

symmetric_design_approach = setting(
    "For symmetric oligomer design, given a point group symmetry specification and "
    "monomer chain length, random starting residue frames are generated for a single "
    "monomer subunit, then n-1 copies are arranged with the specified symmetry. "
    "Because RFdiffusion is equivariant with respect to rotation and chain relabelings "
    "(inherited from RF), symmetry is largely maintained in denoising predictions; "
    "explicit resymmetrization at each step changes structures only slightly. For "
    "octahedral and icosahedral architectures, only the smallest subset of monomers "
    "required to generate the full assembly is explicitly modeled.",
    title="Symmetric oligomer generation approach",
)

# --- Claims ---

symmetric_high_success = claim(
    "Despite not being trained on symmetric inputs, RFdiffusion generates symmetric "
    "oligomers with high in silico success rates, particularly when guided by an "
    "auxiliary inter- and intrachain contact potential. RFdiffusion designs are nearly "
    "indistinguishable from AF2 predictions of the structures adopted by the designed "
    "sequences, and many show little resemblance to previously solved protein structures.",
    title="High in silico success for symmetric oligomers",
    background=[symmetric_design_approach, in_silico_success_definition],
)

novel_oligomeric_topologies = claim(
    "Several of the oligomeric topologies generated by RFdiffusion are not seen in "
    "the PDB, including two-layer beta barrels (C10 symmetry) and complex mixed "
    "alpha/beta topologies (C8 symmetry, closest TM-align to PDB: 0.47 and 0.43).",
    title="Novel oligomeric topologies not in PDB",
)

sec_validation_oligomers = claim(
    "Of 608 designs selected for experimental characterization, at least 87 had "
    "oligomerization states closely consistent with the design models by size-exclusion "
    "chromatography (SEC) within the 95% confidence interval (126 within the 99% CI).",
    title="SEC validates oligomeric states",
    metadata={
        "figure": "artifacts/images/057ac95503218142d1bd88466d07855947b2fafdb2a21d7bd8bac1057bdd998a.jpg",
        "caption": "Fig. 3 | Design and experimental characterization of symmetric oligomers. Cyclic (C3, C6, C8), dihedral (D3, D4), and icosahedral assemblies with nsEM validation.",
    },
)

nsem_validates_cyclic = claim(
    "Negative stain electron microscopy (nsEM) characterization of cyclic oligomers "
    "showed distinct particles with shapes resembling design models. A C3 design "
    "(HE0822, 350 residues/subunit, 1050 total) showed 2D class averages consistent "
    "with top and side views, and a 3D reconstruction with the distinctive pinwheel "
    "shape matching the design. C5 and C6 designs with >750 residues also showed "
    "consistent 2D class averages.",
    title="nsEM confirms cyclic oligomer structures",
    metadata={
        "figure": "artifacts/images/057ac95503218142d1bd88466d07855947b2fafdb2a21d7bd8bac1057bdd998a.jpg",
        "caption": "Fig. 3 | Design and experimental characterization of symmetric oligomers. Cyclic (C3, C6, C8), dihedral (D3, D4), and icosahedral assemblies with nsEM validation.",
    },
)

expanded_tim_barrels = claim(
    "RFdiffusion designed cyclic oligomers that extend considerably beyond the natural "
    "TIM barrel fold (8 strands, 8 helices): HE0626 is a C6 alpha-beta barrel with "
    "18 strands and 18 helices; HE0675 is a C8 octamer with an inner ring of 16 "
    "strands and outer ring of 16 helices. nsEM 3D reconstructions for both agree "
    "with design models. Natural evolution has explored structural variations of the "
    "classic 8-strand TIM barrel, but RFdiffusion more readily explores global changes "
    "in barrel curvature.",
    title="Expanded TIM barrel-like oligomers beyond natural evolution",
    metadata={
        "figure": "artifacts/images/057ac95503218142d1bd88466d07855947b2fafdb2a21d7bd8bac1057bdd998a.jpg",
        "caption": "Fig. 3 | Design and experimental characterization of symmetric oligomers. Cyclic (C3, C6, C8), dihedral (D3, D4), and icosahedral assemblies with nsEM validation.",
    },
)

dihedral_tetrahedral_icosahedral = claim(
    "RFdiffusion generated structures with dihedral (D2, D3, D4), tetrahedral, and "
    "icosahedral symmetries. SEC confirmed 38 D2, 7 D3, and 3 D4 designs had expected "
    "molecular weights. nsEM 2D class averages and 3D reconstructions of D3 and D4 "
    "designs were congruent with design models. Cryo-EM of D4 design HE0537 closely "
    "matched the design model, recapitulating the ~45° offset between tetrameric subunits.",
    title="Dihedral and higher-order symmetry designs validated",
    metadata={
        "figure": "artifacts/images/057ac95503218142d1bd88466d07855947b2fafdb2a21d7bd8bac1057bdd998a.jpg",
        "caption": "Fig. 3 | Design and experimental characterization of symmetric oligomers. Cyclic (C3, C6, C8), dihedral (D3, D4), and icosahedral assemblies with nsEM validation.",
    },
)

icosahedral_he0902 = claim(
    "Of 48 icosahedra selected for experimental validation, one (HE0902, a 15 nm "
    "diameter highly porous assembly) formed homogeneous particles observed by nsEM. "
    "2D class averages and 3D reconstruction very closely match the design model, with "
    "triangular hubs arrayed around the empty C5 axes. Such large assemblies should be "
    "useful as nanomaterials and vaccine scaffolds.",
    title="Icosahedral assembly HE0902 validated by nsEM",
    metadata={
        "figure": "artifacts/images/057ac95503218142d1bd88466d07855947b2fafdb2a21d7bd8bac1057bdd998a.jpg",
        "caption": "Fig. 3 | Design and experimental characterization of symmetric oligomers. Cyclic (C3, C6, C8), dihedral (D3, D4), and icosahedral assemblies with nsEM validation.",
    },
)

# --- Strategies ---

_strat_symmetric_success = noisy_and(
    [pipeline_description],
    symmetric_high_success,
    reason=(
        "RFdiffusion's symmetric oligomer generation leverages @pipeline_description — "
        "the same diffusion pipeline, but with symmetric copies of the monomer arranged "
        "with specified point group symmetry. The equivariance inherited from RF means "
        "symmetry is naturally maintained during denoising. The auxiliary contact potential "
        "further guides inter-chain interactions."
    ),
    background=[symmetric_design_approach, in_silico_success_definition],
)

# Novel topologies support the claim of generalization
_strat_novel_topologies = noisy_and(
    [symmetric_high_success],
    novel_oligomeric_topologies,
    reason=(
        "The novel topologies (two-layer beta barrels, complex mixed alpha/beta) emerge "
        "from @symmetric_high_success — RFdiffusion generating diverse symmetric oligomers. "
        "Low TM-align scores to PDB (0.47, 0.43) confirm these are genuinely new."
    ),
)

# SEC validates symmetric designs
alt_coincidental_sec_profiles = claim(
    "The SEC elution profiles consistent with expected molecular weights could be "
    "coincidental: non-specific aggregation at similar sizes, or incomplete assembly "
    "with similar apparent mass.",
    title="Alternative: coincidental SEC profiles",
)

_strat_sec_validates = abduction(
    observation=sec_validation_oligomers,
    hypothesis=symmetric_high_success,
    alternative=alt_coincidental_sec_profiles,
    reason=(
        "The observation (@sec_validation_oligomers) that at least 87/608 designs show "
        "SEC profiles consistent with designed oligomeric states supports "
        "@symmetric_high_success. While individual SEC profiles might be coincidental, "
        "the systematic agreement across many designs and symmetry groups makes non-specific "
        "aggregation unlikely as a general explanation."
    ),
)

alt_structural_mimicry_in_nsem = claim(
    "The nsEM 2D class averages and 3D reconstructions showing shapes consistent "
    "with design models could reflect a different structure that happens to have "
    "similar overall dimensions and symmetry.",
    title="Alternative: structural mimicry in nsEM",
)

_strat_nsem_cyclic = abduction(
    observation=nsem_validates_cyclic,
    hypothesis=symmetric_high_success,
    alternative=alt_structural_mimicry_in_nsem,
    reason=(
        "The nsEM observation (@nsem_validates_cyclic) provides direct structural evidence "
        "supporting @symmetric_high_success. The C3 design HE0822 shows 2D class averages "
        "matching both top and side views with the distinctive pinwheel shape, and a 3D "
        "reconstruction with key features matching the design. This level of structural "
        "agreement goes well beyond what would be expected from an alternative structure "
        "with merely similar dimensions."
    ),
)

# Expanded TIM barrels are a notable result from symmetric design
_strat_expanded_tim = noisy_and(
    [symmetric_high_success],
    expanded_tim_barrels,
    reason=(
        "The expanded TIM barrel-like oligomers (HE0626 C6 18-strand/18-helix, HE0675 C8 "
        "16-strand/16-helix) emerge from @symmetric_high_success applied to cyclic "
        "symmetries. nsEM 3D reconstructions confirm the designed structures, demonstrating "
        "that RFdiffusion explores global barrel curvature changes beyond natural evolution."
    ),
)

_strat_dihedral = noisy_and(
    [symmetric_high_success, sec_validation_oligomers],
    dihedral_tetrahedral_icosahedral,
    reason=(
        "The dihedral, tetrahedral, and icosahedral designs extend the same approach "
        "(@symmetric_high_success) to higher-order symmetries. @sec_validation_oligomers "
        "confirms oligomeric states for D2/D3/D4 designs, and nsEM/cryo-EM characterization "
        "(e.g., D4 HE0537 at ~45° offset) provides structural validation that the designed "
        "symmetry is achieved."
    ),
)

alt_disordered_aggregates_mimicking_icosahedral = claim(
    "The nsEM particles could represent disordered aggregates that coincidentally "
    "show icosahedral-like projections.",
    title="Alternative: disordered aggregates mimicking icosahedral symmetry",
)

_strat_icosahedral = abduction(
    observation=icosahedral_he0902,
    hypothesis=symmetric_high_success,
    alternative=alt_disordered_aggregates_mimicking_icosahedral,
    reason=(
        "The observation (@icosahedral_he0902) that HE0902 forms homogeneous particles "
        "with 2D class averages and 3D reconstruction very closely matching the designed "
        "icosahedral model — including triangular hubs around empty C5 axes — provides "
        "strong evidence for @symmetric_high_success. The specific architectural features "
        "rule out disordered aggregation."
    ),
)
